apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bootc-image-builder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bootc-image-builder
    app.kubernetes.io/part-of: bootc-image-builder
  name: bootc-image-builder
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: bootc-image-builder
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bootc-image-builder
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/bootc-image-builder/bootc-image-builder@sha256:a4b866ac6c91b2fdf63c61c972b0494acbe08d943fb925997277bc662179337e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
