apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bootc-image-builder
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/bootc-image-builder/bootc-image-builder@sha256:7567bf18a1c3984b5842dc6ade6ce4714f3f0b751670fb952b25eae2def8eddc
        name: container-image
        resources: {}
status: {}
