apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bootc-image-builder
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/bootc-image-builder/bootc-image-builder@sha256:b0648470bb82e8a6ad39475c14fb4fec98cc4731199275e38b9a3a1c22f0bb27
        name: container-image
        resources: {}
status: {}
