apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bootc-image-builder
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/bootc-image-builder/bootc-image-builder@sha256:c7863b56140bf1c37eac0ee3415897525ab493c7d8482a9f079308ff1b0c98c1
        name: container-image
        resources: {}
status: {}
